apiVersion: v1
kind: Service
metadata:
  name: fluentd-webapp
  namespace: fluentd
  labels:
    mylabelsname: webapp4
spec: 
  selector:
    mylabelsname: webapp4
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: LoadBalancer  