apiVersion: v1
kind: Service
metadata:
  name: service-for-angularweb
spec:
  type: LoadBalancer
  selector:
    app: webapp1
  ports: 
    - name: angularweb-server
      protocol: TCP
      port: 80
      targetPort: 80   
  